# fly.toml app configuration file generated for song-reccy
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'song-reccy'
primary_region = 'ord'

[build]

[env]
  FLASK_ENV = "production"
  PORT = "8080"
  # The SPOTIFY_REDIRECT_URI should be set to your production domain in secrets
  # Example: SPOTIFY_REDIRECT_URI = "https://song-reccy.fly.dev/api/callback"
  # Set this using: fly secrets set SPOTIFY_REDIRECT_URI=https://your-app-name.fly.dev/api/callback

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"

